// words.js
// Shabd (word) database for English to Hinglish replacement.
// Key   = English word/phrase to find (lowercase, will be matched case-insensitively)
// Value = Hinglish (romanized Hindi) replacement
//
// MULTI-WORD PHRASES must come before single words so they are matched first.
// Rule: longer/more-specific entries at the top of each section.

const WORD_MAP = {

  // GREETINGS & FAREWELLS  (phrases before single words)
  "good morning":        "suprabhat",
  "good afternoon":      "shubh dopahar",
  "good evening":        "shubh sandhya",
  "good night":          "shubh ratri",
  "good bye":            "alvida",
  "goodbye":             "alvida",
  "see you later":       "phir milenge",
  "see you":             "phir milenge",
  "take care":           "apna khayal rakhna",
  "welcome":             "swagat hai",
  "hello":               "namaste",
  "hi":                  "namaste",
  "bye":                 "alvida",

  // POLITE WORDS & COMMON RESPONSES
  "thank you very much":  "bahut bahut dhanyavaad",
  "thank you":            "dhanyavaad",
  "thankyou":             "dhanyavaad",
  "thanks a lot":         "bahut shukriya",
  "thanks":               "shukriya",
  "you're welcome":       "koi baat nahin",
  "no problem":           "koi baat nahin",
  "excuse me":            "maafi chahta hoon",
  "i'm sorry":            "mujhe maaf karein",
  "sorry":                "maaf karna",
  "please":               "kripya",
  "of course":            "bilkul",
  "sure":                 "zaroor",
  "maybe":                "shayad",
  "okay":                 "theek hai",
  "ok":                   "theek hai",
  "yes":                  "haan",
  "no":                   "nahin",
  "never":                "kabhi nahin",
  "always":               "hamesha",
  "sometimes":            "kabhi kabhi",
  "again":                "phir se",
  "enough":               "kaafi",
  "together":             "saath mein",
  "quickly":              "jaldi",
  "slowly":               "dheere",
  "here":                 "yahaan",
  "there":                "wahaan",
  "now":                  "abhi",
  "later":                "baad mein",
  "today":                "aaj",
  "tomorrow":             "kal",
  "yesterday":            "kal",       // Hindi uses same word; context decides
  "soon":                 "jald hi",
  "already":              "pehle se",
  "still":                "abhi bhi",
  "also":                 "bhi",
  "only":                 "sirf",
  "just":                 "bas",
  "very":                 "bahut",
  "too":                  "bhi",
  "so":                   "toh",
  "then":                 "phir",
  "but":                  "lekin",
  "because":              "kyunki",
  "if":                   "agar",
  "when":                 "jab",
  "where":                "kahaan",
  "why":                  "kyun",
  "how":                  "kaise",
  "what":                 "kya",
  "who":                  "kaun",
  "which":                "kaun sa",

  // PRONOUNS
  "i":          "main",
  "me":         "mujhe",
  "my":         "mera",
  "mine":       "mera",
  "myself":     "mujhe khud",
  "we":         "hum",
  "our":        "hamara",
  "ours":       "hamara",
  "you":        "aap",
  "your":       "aapka",
  "yours":      "aapka",
  "he":         "voh",
  "him":        "use",
  "his":        "uska",
  "she":        "voh",
  "her":        "use",
  "hers":       "uska",
  "it":         "yeh",
  "its":        "uska",
  "they":       "ve",
  "them":       "unhe",
  "their":      "unka",
  "this":       "yeh",
  "that":       "voh",
  "these":      "ye",
  "those":      "ve",

  // COMMON VERBS  (infinitive / dictionary form)
  "to be":      "hona",
  "to have":    "paas hona",
  "to do":      "karna",
  "to go":      "jaana",
  "to come":    "aana",
  "to eat":     "khaana",
  "to drink":   "peena",
  "to sleep":   "sona",
  "to wake":    "jaagna",
  "to sit":     "baithna",
  "to stand":   "khada hona",
  "to walk":    "chalna",
  "to run":     "daudna",
  "to speak":   "bolna",
  "to say":     "kehna",
  "to listen":  "sunna",
  "to see":     "dekhna",
  "to look":    "dekhna",
  "to read":    "padhna",
  "to write":   "likhna",
  "to work":    "kaam karna",
  "to play":    "khelna",
  "to laugh":   "hasna",
  "to cry":     "rona",
  "to love":    "pyaar karna",
  "to want":    "chahna",
  "to need":    "zaroorat hona",
  "to know":    "jaanna",
  "to think":   "sochna",
  "to feel":    "mehsoos karna",
  "to give":    "dena",
  "to take":    "lena",
  "to bring":   "laana",
  "to send":    "bhejna",
  "to buy":     "khareedna",
  "to sell":    "bechna",
  "to open":    "kholna",
  "to close":   "band karna",
  "to start":   "shuru karna",
  "to stop":    "rukna",
  "to finish":  "khatam karna",
  "to wait":    "intezaar karna",
  "to help":    "madad karna",
  "to ask":     "poochna",
  "to answer":  "jawab dena",
  "to forget":  "bhoolna",
  "to remember": "yaad karna",
  "to learn":   "seekhna",
  "to teach":   "padhana",
  "to make":    "banana",
  "to break":   "todna",
  "to find":    "dhoondhna",
  "to lose":    "kho dena",
  "to win":     "jeenna",
  "to meet":    "milna",
  "to leave":   "jaana",
  "to return":  "wapas aana",
  "to stay":    "rukna",
  "to live":    "rehna",
  "to die":     "marna",
  "to wake up": "uthna",
  "to get up":  "uthna",
  "to use":     "istemaal karna",
  "to change":  "badalna",
  "to choose":  "chunna",
  "to try":     "koshish karna",
  "to understand": "samajhna",
  "to explain": "samjhana",
  "to show":    "dikhaana",
  "to hear":    "sunna",
  "to call":    "bulaana",
  "to pay":     "daam dena",
  "to cook":    "pakana",
  "to clean":   "saaf karna",
  "to travel":  "safar karna",
  "to sing":    "gaana",
  "to dance":   "naachna",
  "to swim":    "tairna",
  "to fight":   "ladna",

  // COMMON ADJECTIVES
  "good":         "accha",
  "bad":          "bura",
  "great":        "bahut accha",
  "wonderful":    "shandar",
  "beautiful":    "sundar",
  "ugly":         "badsoorat",
  "big":          "bada",
  "small":        "chota",
  "tall":         "lamba",
  "short":        "chhota",
  "long":         "lamba",
  "wide":         "chauda",
  "narrow":       "tanga",
  "heavy":        "bhaari",
  "light":        "halka",
  "fast":         "tez",
  "slow":         "dheema",
  "hot":          "garam",
  "cold":         "thanda",
  "warm":         "gunguna",
  "wet":          "geela",
  "dry":          "sukha",
  "clean":        "saaf",
  "dirty":        "ganda",
  "old":          "puraana",
  "new":          "naya",
  "young":        "jawan",
  "strong":       "mazboot",
  "weak":         "kamzor",
  "hard":         "sakht",
  "soft":         "naram",
  "easy":         "aasaan",
  "difficult":    "mushkil",
  "happy":        "khush",
  "sad":          "udaas",
  "angry":        "gussa",
  "scared":       "dara hua",
  "tired":        "thaka hua",
  "hungry":       "bhuukha",
  "thirsty":      "pyaasa",
  "sick":         "bimaar",
  "healthy":      "tandrust",
  "rich":         "ameer",
  "poor":         "ghareeb",
  "smart":        "tez",
  "foolish":      "bevakoof",
  "kind":         "dayalu",
  "cruel":        "zaalim",
  "honest":       "imaandaar",
  "lazy":         "aalsami",
  "busy":         "vyast",
  "free":         "azaad",
  "right":        "sahi",
  "wrong":        "galat",
  "true":         "sach",
  "false":        "jhooth",
  "important":    "zaroori",
  "necessary":    "zaroori",
  "possible":     "mumkin",
  "impossible":   "namumkin",
  "same":         "ek jaisa",
  "different":    "alag",
  "ready":        "taiyaar",
  "complete":     "poora",
  "empty":        "khaali",
  "full":         "bhara hua",
  "open":         "khula",
  "closed":       "band",
  "near":         "paas",
  "far":          "door",
  "first":        "pehla",
  "last":         "aakhri",
  "next":         "agla",
  "only":         "sirf",
  "special":      "khaas",
  "own":          "apna",
  "favorite":     "pasandida",

  // FAMILY & RELATIONSHIPS
  "mother":          "maa",
  "mom":             "maa",
  "father":          "pita",
  "dad":             "papa",
  "brother":         "bhai",
  "sister":          "behen",
  "son":             "beta",
  "daughter":        "beti",
  "grandfather":     "dada",
  "grandmother":     "dadi",
  "maternal grandfather": "naana",
  "maternal grandmother": "naani",
  "uncle":           "chacha",
  "aunt":            "chachi",
  "husband":         "pati",
  "wife":            "patni",
  "child":           "bachcha",
  "children":        "bachche",
  "baby":            "shishu",
  "family":          "parivaar",
  "friend":          "dost",
  "enemy":           "dushman",
  "neighbor":        "padosi",
  "teacher":         "adhyaapak",
  "student":         "vidyaarthi",
  "doctor":          "daktar",
  "nurse":           "nurse",
  "police":          "police",
  "soldier":         "sainik",
  "king":            "raja",
  "queen":           "rani",
  "god":             "ishvar",
  "person":          "insaan",
  "people":          "log",
  "man":             "aadmi",
  "woman":           "aurat",
  "boy":             "ladka",
  "girl":            "ladki",

  // BODY PARTS
  "head":       "sir",
  "hair":       "baal",
  "face":       "chehra",
  "eye":        "aankh",
  "eyes":       "aankhein",
  "ear":        "kaan",
  "nose":       "naak",
  "mouth":      "munh",
  "tooth":      "daant",
  "teeth":      "daant",
  "tongue":     "zubaan",
  "neck":       "gardan",
  "shoulder":   "kandha",
  "chest":      "seena",
  "back":       "peeth",
  "stomach":    "pet",
  "hand":       "haath",
  "hands":      "haath",
  "finger":     "ungali",
  "thumb":      "angutha",
  "arm":        "baazoo",
  "leg":        "taang",
  "foot":       "paer",
  "feet":       "paer",
  "knee":       "ghutna",
  "heart":      "dil",
  "blood":      "khoon",
  "skin":       "tvacha",
  "bone":       "haddi",
  "voice":      "aawaaz",

  // FOOD & DRINK
  "food":         "khaana",
  "water":        "paani",
  "milk":         "doodh",
  "tea":          "chai",
  "coffee":       "coffee",
  "juice":        "ras",
  "sugar":        "cheeni",
  "salt":         "namak",
  "oil":          "tel",
  "butter":       "makhan",
  "bread":        "roti",
  "rice":         "chawal",
  "lentils":      "daal",
  "vegetable":    "sabzi",
  "vegetables":   "sabziyaan",
  "meat":         "maas",
  "chicken":      "murga",
  "fish":         "machli",
  "egg":          "anda",
  "eggs":         "ande",
  "apple":        "seb",
  "banana":       "kela",
  "mango":        "aam",
  "orange":       "santara",
  "grape":        "angoor",
  "potato":       "aalu",
  "onion":        "pyaaz",
  "tomato":       "tamatar",
  "garlic":       "lehsun",
  "ginger":       "adrak",
  "pepper":       "mirch",
  "spice":        "masala",
  "sweet":        "meetha",
  "bitter":       "kadwa",
  "sour":         "khatta",
  "salty":        "namkeen",
  "spicy":        "teekha",
  "delicious":    "swaadisht",
  "meal":         "khaana",
  "breakfast":    "naashta",
  "lunch":        "dopahar ka khaana",
  "dinner":       "raat ka khaana",
  "snack":        "naashta",
  "kitchen":      "rasoi",
  "plate":        "thaali",
  "cup":          "pyaala",
  "glass":        "gilaas",
  "bowl":         "katori",
  "bottle":       "botal",
  "bag":          "thaila",

  // NATURE & ENVIRONMENT
  "sky":          "aakaash",
  "sun":          "suraj",
  "moon":         "chaand",
  "star":         "taara",
  "stars":        "taare",
  "cloud":        "baadal",
  "rain":         "baarish",
  "wind":         "hawa",
  "storm":        "toofaan",
  "snow":         "barf",
  "ice":          "barf",
  "fire":         "aag",
  "earth":        "dharti",
  "land":         "zameen",
  "mountain":     "pahad",
  "river":        "nadi",
  "lake":         "jheel",
  "sea":          "samundar",
  "ocean":        "mahasagar",
  "forest":       "jungle",
  "tree":         "ped",
  "flower":       "phool",
  "fruit":        "phal",
  "grass":        "ghaas",
  "stone":        "patthar",
  "sand":         "baalu",
  "air":          "hawa",
  "light":        "roshni",
  "darkness":     "andhera",
  "shadow":       "parchhaaein",
  "bird":         "chidiya",
  "animal":       "janwar",
  "horse":        "ghoda",
  "cow":          "gaay",
  "elephant":     "haathi",
  "lion":         "sher",
  "tiger":        "baagh",
  "snake":        "saanp",
  "dog":          "kutta",
  "cat":          "billi",
  "rat":          "chooha",

  // PLACES & DIRECTIONS
  "house":        "ghar",
  "home":         "ghar",
  "room":         "kamra",
  "door":         "darvaaza",
  "window":       "khidki",
  "wall":         "deevar",
  "floor":        "zameen",
  "roof":         "chhat",
  "street":       "gali",
  "road":         "sadak",
  "city":         "sheher",
  "town":         "kasba",
  "village":      "gaanv",
  "country":      "desh",
  "market":       "bazaar",
  "shop":         "dukaan",
  "store":        "dukaan",
  "hospital":     "aspataal",
  "school":       "vidyaalay",
  "college":      "college",
  "temple":       "mandir",
  "mosque":       "masjid",
  "church":       "girja ghar",
  "park":         "baag",
  "garden":       "bagicha",
  "station":      "station",
  "airport":      "havai adda",
  "hotel":        "hotel",
  "bank":         "bank",
  "north":        "uttar",
  "south":        "dakshin",
  "east":         "poorab",
  "west":         "paschim",
  "left":         "baayein",
  "right":        "daayein",
  "straight":     "seedha",
  "up":           "upar",
  "down":         "neeche",
  "inside":       "andar",
  "outside":      "bahar",
  "front":        "aage",
  "behind":       "peeche",
  "between":      "beech mein",
  "near":         "paas",
  "far":          "door",

  // TIME
  "time":         "samay",
  "second":       "second",
  "minute":       "minute",
  "hour":         "ghanta",
  "day":          "din",
  "week":         "hafta",
  "month":        "mahina",
  "year":         "saal",
  "morning":      "subah",
  "afternoon":    "dopahar",
  "evening":      "shaam",
  "night":        "raat",
  "midnight":     "aadhi raat",
  "monday":       "somvaar",
  "tuesday":      "mangalvaar",
  "wednesday":    "budhvaar",
  "thursday":     "guruvaar",
  "friday":       "shukravaar",
  "saturday":     "shanivaar",
  "sunday":       "ravivaar",
  "january":      "janvari",
  "february":     "farvari",
  "march":        "maarch",
  "april":        "aprail",
  "may":          "mai",
  "june":         "joon",
  "july":         "julaai",
  "august":       "agast",
  "september":    "sitambar",
  "october":      "aktubar",
  "november":     "navambar",
  "december":     "disambar",
  "spring":       "basant",
  "summer":       "garmi",
  "autumn":       "patjhad",
  "winter":       "sardi",

  // NUMBERS
  "zero":         "shunya",
  "one":          "ek",
  "two":          "do",
  "three":        "teen",
  "four":         "chaar",
  "five":         "paanch",
  "six":          "cheh",
  "seven":        "saat",
  "eight":        "aath",
  "nine":         "nau",
  "ten":          "das",
  "eleven":       "gyaarah",
  "twelve":       "baarah",
  "thirteen":     "terah",
  "fourteen":     "chaudah",
  "fifteen":      "pandrah",
  "sixteen":      "solah",
  "seventeen":    "satrah",
  "eighteen":     "athaara",
  "nineteen":     "unnis",
  "twenty":       "bees",
  "thirty":       "tees",
  "forty":        "chaalis",
  "fifty":        "pachaas",
  "sixty":        "saath",
  "seventy":      "sattar",
  "eighty":       "assi",
  "ninety":       "nabbe",
  "hundred":      "sau",
  "thousand":     "hazaar",
  "million":      "das laakh",
  "first":        "pehla",
  "second":       "doosra",
  "third":        "teesra",
  "last":         "aakhri",
  "half":         "aadha",
  "quarter":      "chauthaai",

  // COLOURS
  "red":          "laal",
  "blue":         "neela",
  "green":        "hara",
  "yellow":       "peela",
  "orange":       "narangi",
  "purple":       "baingni",
  "pink":         "gulabi",
  "black":        "kaala",
  "white":        "safed",
  "grey":         "slaati",
  "gray":         "slaati",
  "brown":        "bhoora",
  "golden":       "sona",
  "silver":       "chaandi",

  // CLOTHES & APPEARANCE
  "clothes":      "kapde",
  "shirt":        "kameez",
  "pants":        "patloon",
  "dress":        "poshak",
  "shoes":        "joote",
  "hat":          "topi",
  "coat":         "coat",
  "scarf":        "dupatta",
  "ring":         "angoothi",
  "watch":        "ghadi",
  "glasses":      "chashma",

  // COMMON OBJECTS
  "book":         "kitaab",
  "pen":          "kalam",
  "paper":        "kaagaz",
  "phone":        "fone",
  "computer":     "computer",
  "car":          "gaadi",
  "bicycle":      "cycle",
  "bus":          "bus",
  "train":        "rail gaadi",
  "airplane":     "hawai jahaaz",
  "boat":         "naav",
  "key":          "chaabi",
  "money":        "paisa",
  "coin":         "sikka",
  "price":        "daam",
  "work":         "kaam",
  "job":          "naukri",
  "letter":       "khat",
  "message":      "sandesh",
  "news":         "khabar",
  "picture":      "tasveer",
  "music":        "sangeet",
  "song":         "gaana",
  "game":         "khel",
  "language":     "bhaasha",
  "word":         "shabd",
  "name":         "naam",
  "number":       "number",
  "question":     "sawaal",
  "answer":       "jawaab",
  "problem":      "mushkil",
  "idea":         "vichaar",
  "plan":         "yojana",
  "power":        "shakti",
  "war":          "yudh",
  "peace":        "shanti",
  "life":         "zindagi",
  "death":        "maut",
  "dream":        "sapna",
  "hope":         "umeed",
  "fear":         "dar",
  "anger":        "gussa",
  "joy":          "khushi",
  "pain":         "dard",
  "love":         "pyaar",
  "hate":         "nafrat",
  "truth":        "sach",
  "lie":          "jhooth",
  "path":         "raasta",
  "way":          "raasta",
  "world":        "duniya",
  "mind":         "mann",
  "soul":         "aatma",
  "body":         "shareer",
  "nature":       "prakrati",
  "history":      "itihaas",
  "story":        "kahani",
  "health":       "sehat",
  "disease":      "bimari",
  "medicine":     "dawa",
  "hospital":     "aspataal",
  "society":      "samaaj",
  "government":   "sarkaar",
  "law":          "kanoon",
  "justice":      "nyaay",
  "freedom":      "azaadi",
  "knowledge":    "gyaan",
  "education":    "shiksha",
  "religion":     "dharm",
  "festival":     "tyohaar",
  "marriage":     "shaadi",
  "death":        "maut",
  "birth":        "janam",
  "age":          "umra",

};
