// words.js
// This is your shabd (word) database for English to Hinglish replacement.
// Key   = the English word to find (lowercase)
// Value = the Hinglish replacement

const WORD_MAP = {
  // --- Common Nouns ---
  "water": "paani",
  "fire": "aag",
  "house": "ghar",
  "food": "khaana",
  "dog": "kutta",
  "cat": "billi",
  "book": "kitaab",
  "road": "sadak",
  "city": "sheher",
  "village": "gaanv",
  "school": "vidyalay",
  "money": "paisa",
  "time": "samay",
  "work": "kaam",
  "day": "din",
  "night": "raat",
  "sky": "aakaash",
  "sun": "suraj",
  "moon": "chaand",
  "friend": "dost",
  "family": "parivaar",
  "heart": "dil",
  "hand": "haath",
  "eye": "aankh",
  "voice": "aawaaz",
  "dream": "sapna",
  "life": "zindagi",
  "love": "pyaar",
  "truth": "sach",
  "path": "raasta",
  "car": "gaadi",
  "mother": "maa",
  "father": "pita",
  "brother": "bhai",
  "sister": "behen",
  "man": "aadmi",
  "woman": "aurat",
  "boy": "ladka",
  "girl": "ladki",
  "tree": "ped",
  "fruit": "phal",
  "flower": "phool",
  "earth": "dharti",
  "river": "nadi",
  "sea": "samundar",
  "bird": "chidiya",
  "animal": "janwar",
  "milk": "doodh",
  "tea": "chai",
  "sugar": "cheeni",
  "salt": "namak",
  "bread": "roti",
  "rice": "chawal",
  "lentils": "daal",
  "vegetable": "sabzi",
  "meat": "maas",
  "chicken": "murga",
  "fish": "machli",
  "egg": "anda",
  "apple": "seb",
  "banana": "kela",
  "mango": "aam",
  "orange": "santara",
  "potato": "aalu",
  "onion": "pyaaz",
  "tomato": "tamatar",
  "garlic": "lehsun",
  "ginger": "adrak",

  // --- Numbers ---
  "one": "ek",
  "two": "do",
  "three": "teen",
  "four": "chaar",
  "five": "paanch",
  "six": "cheh",
  "seven": "saat",
  "eight": "aath",
  "nine": "nau",
  "ten": "das",

  // --- Greetings & Polite Phrases ---
  "hello": "namaste",
  "goodbye": "alvida",
  "thank you": "dhanyavaad",
  "thankyou": "dhanyavaad",
  "thanks": "dhanyavaad",
  "please": "kripya",
  "sorry": "maaf karna",
  "yes": "haan",
  "no": "nahin",
  "good morning": "suprabhat",
  "good evening": "shubh sandhya",
  "shubh ratri": "shubh ratri",

  // --- Questions & Common Sentences ---
  "aap kaise hain": "aap kaise hain",
  "main theek hoon": "main theek hoon",
  "aapka naam kya hai": "aapka naam kya hai",
  "mera naam hai": "mera naam hai",
  "aap kahan se hain": "aap kahan se hain",
  "main se hoon": "main se hoon",
  "aap kya karte hain": "aap kya karte hain",
  "main ek hoon": "main ek hoon",
  "yah kya hai": "yah kya hai",
  "yah ek hai": "yah ek hai",
  "vah kya hai": "vah kya hai",
  "vah ek hai": "vah ek hai",
  "yah kitna hai": "yah kitna hai",
  "vah kitna hai": "vah kitna hai",
  "kitne": "kitne",
  "ye kitne hain": "ye kitne hain",
  "ve kitne hain": "ve kitne hain",
  "aapke paas kitne hain": "aapke paas kitne hain",

  // --- Pronouns & Helping Verbs (Phrases) ---
  "mere paas hai": "mere paas hai",
  "mere paas nahin hai": "mere paas nahin hai",
  "mujhe chahiye": "mujhe chahiye",
  "mujhe nahin chahiye": "mujhe nahin chahiye",
  "mujhe pasand hai": "mujhe pasand hai",
  "mujhe pasand nahin hai": "mujhe pasand nahin hai",
  "mujhe pyaar hai": "mujhe pyaar hai",
  "mujhe pyaar nahin hai": "mujhe pyaar nahin hai",
  "mujhe nafrat hai": "mujhe nafrat hai",
  "mujhe nafrat nahin hai": "mujhe nafrat nahin hai",
  "mujhe zaroorat hai": "mujhe zaroorat hai",
  "mujhe zaroorat nahin hai": "mujhe zaroorat nahin hai",
  "mujhe karna hai": "mujhe karna hai",
  "mujhe nahin karna hai": "mujhe nahin karna hai",
  "main kar sakta hoon": "main kar sakta hoon",
  "main nahin kar sakta": "main nahin kar sakta",
  "main nahin kar sakta": "main nahin kar sakta",
  "main karunga": "main karunga",
  "main nahin karunga": "main nahin karunga",
  "main nahin karunga": "main nahin karunga",
  "main karta": "main karta",
  "main nahin karta": "main nahin karta",
  "main nahin karta": "main nahin karta",
  "mujhe karna chahiye": "mujhe karna chahiye",
  "mujhe nahin karna chahiye": "mujhe nahin karna chahiye",
  "mujhe nahin karna chahiye": "mujhe nahin karna chahiye",
  "mujhe karna hi hai": "mujhe karna hi hai",
  "mujhe nahin karna hai": "mujhe nahin karna hai",
  "mujhe nahin karna hai": "mujhe nahin karna hai",
  "main kar sakta hoon": "main kar sakta hoon",
  "main nahin kar sakta": "main nahin kar sakta",
  "main kar sakta hoon": "main kar sakta hoon",
  "main nahin kar sakta": "main nahin kar sakta",
  "main kar sakta tha": "main kar sakta tha",
  "main nahin kar sakta tha": "main nahin kar sakta tha",
  "main nahin kar sakta tha": "main nahin kar sakta tha"
};
